### ISSUE TITLE
ガバガバ文字数カウントを何とかする

### ISSUE THREAD

**Issue by paralleltree** [paralleltree/ProgressiveTweet#1]
## 概要

改行で2文字分になったりurlがそのままカウントされることを改善する。
## 対応
- [x] 改行を1文字としてカウント
- [x] URLの短縮カウント

**Comment by paralleltree** [comment]
改行の2文字カウントは`\r\n`によるもの。
- ~~140 - Text.Length + Text.Count(p => p == '\r')~~ (時間がかかる)
- ~~140 - Text.Replace("\r\n", "\n").Length~~
- 140 - Text.Replace("\r", "").Length

~~あたりで何とかなる？~~

**Comment by kb10uy** [comment]
\rだけをReplaceで消去するほうがいいかもしれない
https://github.com/kb10uy/Kbtter4/blob/master/Kbtter4/ViewModels/MainWindowViewModel.cs#L327

**Comment by paralleltree** [comment]
なるほど。URL検出も参考にしてみます。

**Comment by paralleltree** [comment]
ドメインあまり考えずに雑に実装
